#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 99
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 3
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  sym__identifier = 1,
  anon_sym_rule = 2,
  anon_sym_and = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_let = 6,
  anon_sym_EQ = 7,
  anon_sym__ = 8,
  anon_sym_eof = 9,
  anon_sym_SQUOTE = 10,
  aux_sym_character_token1 = 11,
  anon_sym_DQUOTE = 12,
  aux_sym_string_token1 = 13,
  aux_sym_string_token2 = 14,
  aux_sym_string_token3 = 15,
  aux_sym_escape_sequence_token1 = 16,
  aux_sym_escape_sequence_token2 = 17,
  aux_sym_escape_sequence_token3 = 18,
  aux_sym_escape_sequence_token4 = 19,
  anon_sym_LBRACK = 20,
  anon_sym_CARET = 21,
  anon_sym_RBRACK = 22,
  anon_sym_DASH = 23,
  anon_sym_POUND = 24,
  anon_sym_STAR = 25,
  anon_sym_PLUS = 26,
  anon_sym_QMARK = 27,
  anon_sym_PIPE = 28,
  anon_sym_LPAREN = 29,
  anon_sym_RPAREN = 30,
  anon_sym_as = 31,
  anon_sym_refill = 32,
  anon_sym_parse = 33,
  anon_sym_shortest = 34,
  sym_comment = 35,
  sym_ocaml = 36,
  sym_lexer_definition = 37,
  sym_action = 38,
  sym_named_regexp = 39,
  sym__regexp = 40,
  sym_character = 41,
  sym_string = 42,
  sym_escape_sequence = 43,
  sym_character_set = 44,
  sym_character_range = 45,
  sym_regexp_difference = 46,
  sym_regexp_repetition = 47,
  sym_regexp_strict_repetition = 48,
  sym_regexp_option = 49,
  sym_regexp_alternative = 50,
  sym_regexp_concatenation = 51,
  sym_parenthesized_regexp = 52,
  sym_aliased_regexp = 53,
  sym_refill_handler = 54,
  sym_lexer_entry = 55,
  sym_lexer_case = 56,
  aux_sym_lexer_definition_repeat1 = 57,
  aux_sym_lexer_definition_repeat2 = 58,
  aux_sym_string_repeat1 = 59,
  aux_sym_character_set_repeat1 = 60,
  aux_sym_lexer_entry_repeat1 = 61,
  aux_sym_lexer_entry_repeat2 = 62,
  alias_sym_lexer_argument = 63,
  alias_sym_lexer_entry_name = 64,
  alias_sym_regexp_name = 65,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__identifier] = "_identifier",
  [anon_sym_rule] = "rule",
  [anon_sym_and] = "and",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym__] = "any",
  [anon_sym_eof] = "eof",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_character_token1] = "character_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "escape_sequence",
  [aux_sym_string_token3] = "escape_sequence",
  [aux_sym_escape_sequence_token1] = "escape_sequence_token1",
  [aux_sym_escape_sequence_token2] = "escape_sequence_token2",
  [aux_sym_escape_sequence_token3] = "escape_sequence_token3",
  [aux_sym_escape_sequence_token4] = "escape_sequence_token4",
  [anon_sym_LBRACK] = "[",
  [anon_sym_CARET] = "^",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH] = "-",
  [anon_sym_POUND] = "#",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_QMARK] = "?",
  [anon_sym_PIPE] = "|",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_as] = "as",
  [anon_sym_refill] = "refill",
  [anon_sym_parse] = "parse",
  [anon_sym_shortest] = "shortest",
  [sym_comment] = "comment",
  [sym_ocaml] = "ocaml",
  [sym_lexer_definition] = "lexer_definition",
  [sym_action] = "action",
  [sym_named_regexp] = "named_regexp",
  [sym__regexp] = "_regexp",
  [sym_character] = "character",
  [sym_string] = "string",
  [sym_escape_sequence] = "escape_sequence",
  [sym_character_set] = "character_set",
  [sym_character_range] = "character_range",
  [sym_regexp_difference] = "regexp_difference",
  [sym_regexp_repetition] = "regexp_repetition",
  [sym_regexp_strict_repetition] = "regexp_strict_repetition",
  [sym_regexp_option] = "regexp_option",
  [sym_regexp_alternative] = "regexp_alternative",
  [sym_regexp_concatenation] = "regexp_concatenation",
  [sym_parenthesized_regexp] = "parenthesized_regexp",
  [sym_aliased_regexp] = "aliased_regexp",
  [sym_refill_handler] = "refill_handler",
  [sym_lexer_entry] = "lexer_entry",
  [sym_lexer_case] = "lexer_case",
  [aux_sym_lexer_definition_repeat1] = "lexer_definition_repeat1",
  [aux_sym_lexer_definition_repeat2] = "lexer_definition_repeat2",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_character_set_repeat1] = "character_set_repeat1",
  [aux_sym_lexer_entry_repeat1] = "lexer_entry_repeat1",
  [aux_sym_lexer_entry_repeat2] = "lexer_entry_repeat2",
  [alias_sym_lexer_argument] = "lexer_argument",
  [alias_sym_lexer_entry_name] = "lexer_entry_name",
  [alias_sym_regexp_name] = "regexp_name",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__identifier] = sym__identifier,
  [anon_sym_rule] = anon_sym_rule,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym__] = anon_sym__,
  [anon_sym_eof] = anon_sym_eof,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_character_token1] = aux_sym_character_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = sym_escape_sequence,
  [aux_sym_string_token3] = sym_escape_sequence,
  [aux_sym_escape_sequence_token1] = aux_sym_escape_sequence_token1,
  [aux_sym_escape_sequence_token2] = aux_sym_escape_sequence_token2,
  [aux_sym_escape_sequence_token3] = aux_sym_escape_sequence_token3,
  [aux_sym_escape_sequence_token4] = aux_sym_escape_sequence_token4,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_refill] = anon_sym_refill,
  [anon_sym_parse] = anon_sym_parse,
  [anon_sym_shortest] = anon_sym_shortest,
  [sym_comment] = sym_comment,
  [sym_ocaml] = sym_ocaml,
  [sym_lexer_definition] = sym_lexer_definition,
  [sym_action] = sym_action,
  [sym_named_regexp] = sym_named_regexp,
  [sym__regexp] = sym__regexp,
  [sym_character] = sym_character,
  [sym_string] = sym_string,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_character_set] = sym_character_set,
  [sym_character_range] = sym_character_range,
  [sym_regexp_difference] = sym_regexp_difference,
  [sym_regexp_repetition] = sym_regexp_repetition,
  [sym_regexp_strict_repetition] = sym_regexp_strict_repetition,
  [sym_regexp_option] = sym_regexp_option,
  [sym_regexp_alternative] = sym_regexp_alternative,
  [sym_regexp_concatenation] = sym_regexp_concatenation,
  [sym_parenthesized_regexp] = sym_parenthesized_regexp,
  [sym_aliased_regexp] = sym_aliased_regexp,
  [sym_refill_handler] = sym_refill_handler,
  [sym_lexer_entry] = sym_lexer_entry,
  [sym_lexer_case] = sym_lexer_case,
  [aux_sym_lexer_definition_repeat1] = aux_sym_lexer_definition_repeat1,
  [aux_sym_lexer_definition_repeat2] = aux_sym_lexer_definition_repeat2,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_character_set_repeat1] = aux_sym_character_set_repeat1,
  [aux_sym_lexer_entry_repeat1] = aux_sym_lexer_entry_repeat1,
  [aux_sym_lexer_entry_repeat2] = aux_sym_lexer_entry_repeat2,
  [alias_sym_lexer_argument] = alias_sym_lexer_argument,
  [alias_sym_lexer_entry_name] = alias_sym_lexer_entry_name,
  [alias_sym_regexp_name] = alias_sym_regexp_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_rule] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_eof] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_character_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token3] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_escape_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_refill] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_parse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_shortest] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_ocaml] = {
    .visible = true,
    .named = true,
  },
  [sym_lexer_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [sym_named_regexp] = {
    .visible = true,
    .named = true,
  },
  [sym__regexp] = {
    .visible = false,
    .named = true,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_character_set] = {
    .visible = true,
    .named = true,
  },
  [sym_character_range] = {
    .visible = true,
    .named = true,
  },
  [sym_regexp_difference] = {
    .visible = true,
    .named = true,
  },
  [sym_regexp_repetition] = {
    .visible = true,
    .named = true,
  },
  [sym_regexp_strict_repetition] = {
    .visible = true,
    .named = true,
  },
  [sym_regexp_option] = {
    .visible = true,
    .named = true,
  },
  [sym_regexp_alternative] = {
    .visible = true,
    .named = true,
  },
  [sym_regexp_concatenation] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_regexp] = {
    .visible = true,
    .named = true,
  },
  [sym_aliased_regexp] = {
    .visible = true,
    .named = true,
  },
  [sym_refill_handler] = {
    .visible = true,
    .named = true,
  },
  [sym_lexer_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_lexer_case] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_lexer_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lexer_definition_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_character_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lexer_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lexer_entry_repeat2] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_lexer_argument] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_lexer_entry_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_regexp_name] = {
    .visible = true,
    .named = true,
  },
};

static TSSymbol ts_alias_sequences[6][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_lexer_argument,
  },
  [2] = {
    [0] = alias_sym_regexp_name,
  },
  [3] = {
    [1] = alias_sym_regexp_name,
  },
  [4] = {
    [0] = alias_sym_lexer_entry_name,
  },
  [5] = {
    [2] = alias_sym_regexp_name,
  },
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '\'') ADVANCE(19);
      if (lookahead == '(') ADVANCE(40);
      if (lookahead == ')') ADVANCE(41);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '+') ADVANCE(37);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '?') ADVANCE(38);
      if (lookahead == '[') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == ']') ADVANCE(33);
      if (lookahead == '^') ADVANCE(32);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '|') ADVANCE(39);
      if (lookahead == '}') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == 'u') ADVANCE(5);
      if (lookahead == 'x') ADVANCE(14);
      if (lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == 'x') ADVANCE(14);
      if (lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == '{') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(9);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(30);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(8);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_character_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_character_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token2);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token3);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token4);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '_') ADVANCE(1);
      if (lookahead == 'a') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'p') ADVANCE(5);
      if (lookahead == 'r') ADVANCE(6);
      if (lookahead == 's') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(8);
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(13);
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_eof);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_rule);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_parse);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_refill);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_shortest);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 3},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 3},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 0, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 3},
  [16] = {.lex_state = 0, .external_lex_state = 3},
  [17] = {.lex_state = 0, .external_lex_state = 3},
  [18] = {.lex_state = 0, .external_lex_state = 3},
  [19] = {.lex_state = 0, .external_lex_state = 3},
  [20] = {.lex_state = 0, .external_lex_state = 3},
  [21] = {.lex_state = 0, .external_lex_state = 3},
  [22] = {.lex_state = 0, .external_lex_state = 3},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 3},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 2, .external_lex_state = 3},
  [29] = {.lex_state = 2, .external_lex_state = 3},
  [30] = {.lex_state = 2, .external_lex_state = 3},
  [31] = {.lex_state = 2, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 2},
  [34] = {.lex_state = 3, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 3, .external_lex_state = 2},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 2},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 0, .external_lex_state = 2},
  [53] = {.lex_state = 0, .external_lex_state = 2},
  [54] = {.lex_state = 0, .external_lex_state = 2},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 0, .external_lex_state = 2},
  [59] = {.lex_state = 0, .external_lex_state = 2},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 2},
  [62] = {.lex_state = 0, .external_lex_state = 2},
  [63] = {.lex_state = 0, .external_lex_state = 2},
  [64] = {.lex_state = 0, .external_lex_state = 2},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 0, .external_lex_state = 2},
  [67] = {.lex_state = 0, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 2},
  [69] = {.lex_state = 0, .external_lex_state = 2},
  [70] = {.lex_state = 0, .external_lex_state = 2},
  [71] = {.lex_state = 0, .external_lex_state = 2},
  [72] = {.lex_state = 0, .external_lex_state = 2},
  [73] = {.lex_state = 0, .external_lex_state = 2},
  [74] = {.lex_state = 0, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 0, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 0, .external_lex_state = 4},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 2},
  [81] = {.lex_state = 0, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 2},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 0, .external_lex_state = 4},
  [85] = {.lex_state = 0, .external_lex_state = 2},
  [86] = {.lex_state = 0, .external_lex_state = 2},
  [87] = {.lex_state = 0, .external_lex_state = 2},
  [88] = {.lex_state = 0, .external_lex_state = 2},
  [89] = {.lex_state = 0, .external_lex_state = 2},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 2},
  [92] = {.lex_state = 0, .external_lex_state = 2},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 2},
  [95] = {.lex_state = 0, .external_lex_state = 2},
  [96] = {.lex_state = 0, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token_comment = 0,
  ts_external_token_DQUOTE = 1,
  ts_external_token_ocaml = 2,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_DQUOTE] = anon_sym_DQUOTE,
  [ts_external_token_ocaml] = sym_ocaml,
};

static bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_comment] = true,
    [ts_external_token_DQUOTE] = true,
    [ts_external_token_ocaml] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token_comment] = true,
    [ts_external_token_DQUOTE] = true,
  },
  [4] = {
    [ts_external_token_comment] = true,
    [ts_external_token_ocaml] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
    [anon_sym_rule] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_eof] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [aux_sym_string_token3] = ACTIONS(1),
    [aux_sym_escape_sequence_token1] = ACTIONS(1),
    [aux_sym_escape_sequence_token2] = ACTIONS(1),
    [aux_sym_escape_sequence_token3] = ACTIONS(1),
    [aux_sym_escape_sequence_token4] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_refill] = ACTIONS(1),
    [anon_sym_parse] = ACTIONS(1),
    [anon_sym_shortest] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_ocaml] = ACTIONS(1),
  },
  [1] = {
    [sym_lexer_definition] = STATE(83),
    [sym_action] = STATE(33),
    [sym_named_regexp] = STATE(35),
    [sym_refill_handler] = STATE(86),
    [aux_sym_lexer_definition_repeat1] = STATE(35),
    [anon_sym_rule] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_refill] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(29), 1,
      anon_sym_STAR,
    ACTIONS(31), 1,
      anon_sym_PLUS,
    ACTIONS(33), 1,
      anon_sym_QMARK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 2,
      anon_sym__,
      anon_sym_eof,
    ACTIONS(17), 3,
      anon_sym_LBRACE,
      anon_sym_PIPE,
      anon_sym_RPAREN,
    ACTIONS(15), 4,
      anon_sym_rule,
      anon_sym_let,
      anon_sym_as,
      anon_sym_refill,
    STATE(4), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [60] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(39), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    STATE(4), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [100] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(29), 1,
      anon_sym_STAR,
    ACTIONS(31), 1,
      anon_sym_PLUS,
    ACTIONS(33), 1,
      anon_sym_QMARK,
    ACTIONS(41), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(43), 7,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    STATE(4), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [148] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(29), 1,
      anon_sym_STAR,
    ACTIONS(31), 1,
      anon_sym_PLUS,
    ACTIONS(33), 1,
      anon_sym_QMARK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_PIPE,
    ACTIONS(49), 1,
      anon_sym_as,
    ACTIONS(19), 2,
      anon_sym__,
      anon_sym_eof,
    ACTIONS(45), 3,
      anon_sym_rule,
      anon_sym_let,
      anon_sym_refill,
    STATE(4), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [208] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(29), 1,
      anon_sym_STAR,
    ACTIONS(31), 1,
      anon_sym_PLUS,
    ACTIONS(33), 1,
      anon_sym_QMARK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_PIPE,
    ACTIONS(49), 1,
      anon_sym_as,
    STATE(58), 1,
      sym_action,
    ACTIONS(19), 2,
      anon_sym__,
      anon_sym_eof,
    STATE(4), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [269] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(29), 1,
      anon_sym_STAR,
    ACTIONS(31), 1,
      anon_sym_PLUS,
    ACTIONS(33), 1,
      anon_sym_QMARK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_PIPE,
    ACTIONS(49), 1,
      anon_sym_as,
    ACTIONS(51), 1,
      anon_sym_RPAREN,
    ACTIONS(19), 2,
      anon_sym__,
      anon_sym_eof,
    STATE(4), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [327] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_PIPE,
    STATE(55), 1,
      sym_lexer_case,
    ACTIONS(53), 2,
      anon_sym__,
      anon_sym_eof,
    STATE(6), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [370] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_PIPE,
    STATE(50), 1,
      sym_lexer_case,
    ACTIONS(53), 2,
      anon_sym__,
      anon_sym_eof,
    STATE(6), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [413] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    STATE(42), 1,
      sym_lexer_case,
    ACTIONS(53), 2,
      anon_sym__,
      anon_sym_eof,
    STATE(6), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [453] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    STATE(59), 1,
      sym_lexer_case,
    ACTIONS(53), 2,
      anon_sym__,
      anon_sym_eof,
    STATE(6), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [493] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    STATE(55), 1,
      sym_lexer_case,
    ACTIONS(53), 2,
      anon_sym__,
      anon_sym_eof,
    STATE(6), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [533] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 2,
      anon_sym__,
      anon_sym_eof,
    STATE(3), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [570] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 2,
      anon_sym__,
      anon_sym_eof,
    STATE(7), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [607] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 2,
      anon_sym__,
      anon_sym_eof,
    STATE(2), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [644] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 2,
      anon_sym__,
      anon_sym_eof,
    STATE(5), 12,
      sym__regexp,
      sym_character,
      sym_string,
      sym_character_set,
      sym_regexp_difference,
      sym_regexp_repetition,
      sym_regexp_strict_repetition,
      sym_regexp_option,
      sym_regexp_alternative,
      sym_regexp_concatenation,
      sym_parenthesized_regexp,
      sym_aliased_regexp,
  [681] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(69), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [707] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(73), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [733] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(77), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [759] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(81), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [785] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(85), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [811] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(89), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [837] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(93), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [863] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(97), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [889] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(101), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [915] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(105), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [941] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 7,
      anon_sym_rule,
      anon_sym_let,
      anon_sym__,
      anon_sym_eof,
      anon_sym_as,
      anon_sym_refill,
      sym__identifier,
    ACTIONS(109), 11,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [967] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_DQUOTE,
    ACTIONS(113), 1,
      aux_sym_string_token1,
    ACTIONS(116), 2,
      aux_sym_string_token2,
      aux_sym_string_token3,
    STATE(28), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
    ACTIONS(119), 4,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
  [991] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_DQUOTE,
    ACTIONS(124), 1,
      aux_sym_string_token1,
    ACTIONS(126), 2,
      aux_sym_string_token2,
      aux_sym_string_token3,
    STATE(28), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
    ACTIONS(128), 4,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
  [1015] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      aux_sym_string_token1,
    ACTIONS(134), 2,
      aux_sym_string_token2,
      aux_sym_string_token3,
    STATE(29), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
    ACTIONS(128), 4,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
  [1039] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      aux_sym_string_token1,
    ACTIONS(136), 7,
      anon_sym_DQUOTE,
      aux_sym_string_token2,
      aux_sym_string_token3,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
  [1055] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 7,
      ts_builtin_sym_end,
      anon_sym_rule,
      anon_sym_and,
      anon_sym_LBRACE,
      anon_sym_let,
      anon_sym_PIPE,
      anon_sym_refill,
  [1068] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_refill,
    ACTIONS(142), 1,
      anon_sym_rule,
    STATE(79), 1,
      sym_refill_handler,
    STATE(36), 2,
      sym_named_regexp,
      aux_sym_lexer_definition_repeat1,
  [1088] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      aux_sym_character_token1,
    STATE(80), 1,
      sym_escape_sequence,
    ACTIONS(146), 4,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
  [1104] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_refill,
    ACTIONS(142), 1,
      anon_sym_rule,
    STATE(79), 1,
      sym_refill_handler,
    STATE(52), 2,
      sym_named_regexp,
      aux_sym_lexer_definition_repeat1,
  [1124] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_refill,
    ACTIONS(148), 1,
      anon_sym_rule,
    STATE(92), 1,
      sym_refill_handler,
    STATE(52), 2,
      sym_named_regexp,
      aux_sym_lexer_definition_repeat1,
  [1144] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      aux_sym_character_token1,
    STATE(97), 1,
      sym_escape_sequence,
    ACTIONS(146), 4,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
  [1160] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_SQUOTE,
    ACTIONS(154), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      sym_character,
    STATE(51), 2,
      sym_character_range,
      aux_sym_character_set_repeat1,
  [1177] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 1,
      anon_sym_and,
    STATE(60), 1,
      aux_sym_lexer_definition_repeat2,
    STATE(93), 1,
      sym_action,
  [1196] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
    STATE(49), 1,
      aux_sym_lexer_definition_repeat2,
    STATE(98), 1,
      sym_action,
  [1215] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_PIPE,
    STATE(45), 1,
      aux_sym_lexer_entry_repeat2,
    ACTIONS(162), 3,
      ts_builtin_sym_end,
      anon_sym_and,
      anon_sym_LBRACE,
  [1230] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_PIPE,
    STATE(41), 1,
      aux_sym_lexer_entry_repeat2,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      anon_sym_and,
      anon_sym_LBRACE,
  [1245] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    STATE(39), 1,
      aux_sym_lexer_definition_repeat2,
    STATE(85), 1,
      sym_action,
  [1264] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_SQUOTE,
    ACTIONS(170), 1,
      anon_sym_CARET,
    STATE(66), 1,
      sym_character,
    STATE(57), 2,
      sym_character_range,
      aux_sym_character_set_repeat1,
  [1281] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_PIPE,
    STATE(45), 1,
      aux_sym_lexer_entry_repeat2,
    ACTIONS(172), 3,
      ts_builtin_sym_end,
      anon_sym_and,
      anon_sym_LBRACE,
  [1296] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
    STATE(60), 1,
      aux_sym_lexer_definition_repeat2,
    STATE(81), 1,
      sym_action,
  [1315] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
    STATE(54), 1,
      aux_sym_lexer_definition_repeat2,
    STATE(81), 1,
      sym_action,
  [1334] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
    STATE(46), 1,
      aux_sym_lexer_definition_repeat2,
    STATE(94), 1,
      sym_action,
  [1353] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
    STATE(60), 1,
      aux_sym_lexer_definition_repeat2,
    STATE(94), 1,
      sym_action,
  [1372] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_PIPE,
    STATE(53), 1,
      aux_sym_lexer_entry_repeat2,
    ACTIONS(181), 3,
      ts_builtin_sym_end,
      anon_sym_and,
      anon_sym_LBRACE,
  [1387] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_SQUOTE,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      sym_character,
    STATE(51), 2,
      sym_character_range,
      aux_sym_character_set_repeat1,
  [1404] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_let,
    ACTIONS(188), 2,
      anon_sym_rule,
      anon_sym_refill,
    STATE(52), 2,
      sym_named_regexp,
      aux_sym_lexer_definition_repeat1,
  [1419] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_PIPE,
    STATE(45), 1,
      aux_sym_lexer_entry_repeat2,
    ACTIONS(193), 3,
      ts_builtin_sym_end,
      anon_sym_and,
      anon_sym_LBRACE,
  [1434] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    STATE(60), 1,
      aux_sym_lexer_definition_repeat2,
    STATE(85), 1,
      sym_action,
  [1453] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_PIPE,
    STATE(56), 1,
      aux_sym_lexer_entry_repeat2,
    ACTIONS(193), 3,
      ts_builtin_sym_end,
      anon_sym_and,
      anon_sym_LBRACE,
  [1468] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_PIPE,
    STATE(45), 1,
      aux_sym_lexer_entry_repeat2,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      anon_sym_and,
      anon_sym_LBRACE,
  [1483] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_SQUOTE,
    ACTIONS(195), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      sym_character,
    STATE(51), 2,
      sym_character_range,
      aux_sym_character_set_repeat1,
  [1500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 4,
      ts_builtin_sym_end,
      anon_sym_and,
      anon_sym_LBRACE,
      anon_sym_PIPE,
  [1510] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 4,
      ts_builtin_sym_end,
      anon_sym_and,
      anon_sym_LBRACE,
      anon_sym_PIPE,
  [1520] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_and,
    STATE(60), 1,
      aux_sym_lexer_definition_repeat2,
    ACTIONS(199), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
  [1534] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_SQUOTE,
    STATE(66), 1,
      sym_character,
    STATE(38), 2,
      sym_character_range,
      aux_sym_character_set_repeat1,
  [1548] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym__identifier,
    ACTIONS(206), 1,
      anon_sym_EQ,
    STATE(67), 1,
      aux_sym_lexer_entry_repeat1,
  [1561] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym__identifier,
    ACTIONS(211), 1,
      anon_sym_EQ,
    STATE(63), 1,
      aux_sym_lexer_entry_repeat1,
  [1574] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 3,
      ts_builtin_sym_end,
      anon_sym_and,
      anon_sym_LBRACE,
  [1583] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 3,
      anon_sym_SQUOTE,
      anon_sym_RBRACK,
      anon_sym_DASH,
  [1592] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_SQUOTE,
      anon_sym_RBRACK,
  [1603] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym__identifier,
    ACTIONS(217), 1,
      anon_sym_EQ,
    STATE(63), 1,
      aux_sym_lexer_entry_repeat1,
  [1616] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym__identifier,
    STATE(48), 1,
      sym_lexer_entry,
  [1626] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_SQUOTE,
    STATE(70), 1,
      sym_character,
  [1636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 2,
      anon_sym_SQUOTE,
      anon_sym_RBRACK,
  [1644] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 2,
      anon_sym_parse,
      anon_sym_shortest,
  [1652] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym__identifier,
    STATE(43), 1,
      sym_lexer_entry,
  [1662] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym__identifier,
    STATE(64), 1,
      sym_lexer_entry,
  [1672] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym__identifier,
    STATE(40), 1,
      sym_lexer_entry,
  [1682] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 2,
      anon_sym_EQ,
      sym__identifier,
  [1690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 2,
      anon_sym_parse,
      anon_sym_shortest,
  [1698] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym__identifier,
    STATE(47), 1,
      sym_lexer_entry,
  [1708] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_ocaml,
  [1715] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_rule,
  [1722] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_SQUOTE,
  [1729] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
  [1736] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__identifier,
  [1743] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
  [1750] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym_ocaml,
  [1757] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
  [1764] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_rule,
  [1771] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
  [1778] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_SQUOTE,
  [1785] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
  [1792] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_rule,
  [1799] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_EQ,
  [1806] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_rule,
  [1813] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
  [1820] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
  [1827] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_RBRACE,
  [1834] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym__identifier,
  [1841] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_SQUOTE,
  [1848] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 60,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 148,
  [SMALL_STATE(6)] = 208,
  [SMALL_STATE(7)] = 269,
  [SMALL_STATE(8)] = 327,
  [SMALL_STATE(9)] = 370,
  [SMALL_STATE(10)] = 413,
  [SMALL_STATE(11)] = 453,
  [SMALL_STATE(12)] = 493,
  [SMALL_STATE(13)] = 533,
  [SMALL_STATE(14)] = 570,
  [SMALL_STATE(15)] = 607,
  [SMALL_STATE(16)] = 644,
  [SMALL_STATE(17)] = 681,
  [SMALL_STATE(18)] = 707,
  [SMALL_STATE(19)] = 733,
  [SMALL_STATE(20)] = 759,
  [SMALL_STATE(21)] = 785,
  [SMALL_STATE(22)] = 811,
  [SMALL_STATE(23)] = 837,
  [SMALL_STATE(24)] = 863,
  [SMALL_STATE(25)] = 889,
  [SMALL_STATE(26)] = 915,
  [SMALL_STATE(27)] = 941,
  [SMALL_STATE(28)] = 967,
  [SMALL_STATE(29)] = 991,
  [SMALL_STATE(30)] = 1015,
  [SMALL_STATE(31)] = 1039,
  [SMALL_STATE(32)] = 1055,
  [SMALL_STATE(33)] = 1068,
  [SMALL_STATE(34)] = 1088,
  [SMALL_STATE(35)] = 1104,
  [SMALL_STATE(36)] = 1124,
  [SMALL_STATE(37)] = 1144,
  [SMALL_STATE(38)] = 1160,
  [SMALL_STATE(39)] = 1177,
  [SMALL_STATE(40)] = 1196,
  [SMALL_STATE(41)] = 1215,
  [SMALL_STATE(42)] = 1230,
  [SMALL_STATE(43)] = 1245,
  [SMALL_STATE(44)] = 1264,
  [SMALL_STATE(45)] = 1281,
  [SMALL_STATE(46)] = 1296,
  [SMALL_STATE(47)] = 1315,
  [SMALL_STATE(48)] = 1334,
  [SMALL_STATE(49)] = 1353,
  [SMALL_STATE(50)] = 1372,
  [SMALL_STATE(51)] = 1387,
  [SMALL_STATE(52)] = 1404,
  [SMALL_STATE(53)] = 1419,
  [SMALL_STATE(54)] = 1434,
  [SMALL_STATE(55)] = 1453,
  [SMALL_STATE(56)] = 1468,
  [SMALL_STATE(57)] = 1483,
  [SMALL_STATE(58)] = 1500,
  [SMALL_STATE(59)] = 1510,
  [SMALL_STATE(60)] = 1520,
  [SMALL_STATE(61)] = 1534,
  [SMALL_STATE(62)] = 1548,
  [SMALL_STATE(63)] = 1561,
  [SMALL_STATE(64)] = 1574,
  [SMALL_STATE(65)] = 1583,
  [SMALL_STATE(66)] = 1592,
  [SMALL_STATE(67)] = 1603,
  [SMALL_STATE(68)] = 1616,
  [SMALL_STATE(69)] = 1626,
  [SMALL_STATE(70)] = 1636,
  [SMALL_STATE(71)] = 1644,
  [SMALL_STATE(72)] = 1652,
  [SMALL_STATE(73)] = 1662,
  [SMALL_STATE(74)] = 1672,
  [SMALL_STATE(75)] = 1682,
  [SMALL_STATE(76)] = 1690,
  [SMALL_STATE(77)] = 1698,
  [SMALL_STATE(78)] = 1708,
  [SMALL_STATE(79)] = 1715,
  [SMALL_STATE(80)] = 1722,
  [SMALL_STATE(81)] = 1729,
  [SMALL_STATE(82)] = 1736,
  [SMALL_STATE(83)] = 1743,
  [SMALL_STATE(84)] = 1750,
  [SMALL_STATE(85)] = 1757,
  [SMALL_STATE(86)] = 1764,
  [SMALL_STATE(87)] = 1771,
  [SMALL_STATE(88)] = 1778,
  [SMALL_STATE(89)] = 1785,
  [SMALL_STATE(90)] = 1792,
  [SMALL_STATE(91)] = 1799,
  [SMALL_STATE(92)] = 1806,
  [SMALL_STATE(93)] = 1813,
  [SMALL_STATE(94)] = 1820,
  [SMALL_STATE(95)] = 1827,
  [SMALL_STATE(96)] = 1834,
  [SMALL_STATE(97)] = 1841,
  [SMALL_STATE(98)] = 1848,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regexp_alternative, 3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regexp_alternative, 3),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regexp_difference, 3),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regexp_difference, 3),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regexp_concatenation, 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regexp_concatenation, 2),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_named_regexp, 4, .production_id = 3),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_set, 4),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_set, 4),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_aliased_regexp, 3, .production_id = 5),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aliased_regexp, 3, .production_id = 5),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regexp_option, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regexp_option, 2),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_set, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_set, 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__regexp, 1, .production_id = 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__regexp, 1, .production_id = 2),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character, 3),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_regexp, 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_regexp, 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regexp_strict_repetition, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regexp_strict_repetition, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regexp_repetition, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regexp_repetition, 2),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(28),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(28),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(31),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 1),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexer_definition, 6),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexer_definition, 2),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexer_entry, 7, .production_id = 4),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexer_entry, 6, .production_id = 4),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexer_definition, 5),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lexer_entry_repeat2, 2),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lexer_entry_repeat2, 2), SHIFT_REPEAT(11),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexer_definition, 4),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexer_definition, 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexer_entry, 4, .production_id = 4),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_character_set_repeat1, 2), SHIFT_REPEAT(37),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_character_set_repeat1, 2),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lexer_definition_repeat1, 2),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lexer_definition_repeat1, 2), SHIFT_REPEAT(82),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexer_entry, 5, .production_id = 4),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexer_case, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lexer_definition_repeat2, 2),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lexer_definition_repeat2, 2), SHIFT_REPEAT(73),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lexer_entry_repeat1, 2), SHIFT_REPEAT(75),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lexer_entry_repeat1, 2),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_character_set_repeat1, 1),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_range, 3),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lexer_entry_repeat1, 1, .production_id = 1),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [235] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_refill_handler, 4),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexer_definition, 7),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_ocamllex_external_scanner_create(void);
void tree_sitter_ocamllex_external_scanner_destroy(void *);
bool tree_sitter_ocamllex_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_ocamllex_external_scanner_serialize(void *, char *);
void tree_sitter_ocamllex_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ocamllex(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__identifier,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_ocamllex_external_scanner_create,
      tree_sitter_ocamllex_external_scanner_destroy,
      tree_sitter_ocamllex_external_scanner_scan,
      tree_sitter_ocamllex_external_scanner_serialize,
      tree_sitter_ocamllex_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
